/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_fintrack;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import j_fintrack.ReportsPanel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.plot.PiePlot;
import java.awt.Color;
import java.awt.BasicStroke;


/**
 *
 * @author darsh
 */
public class java_fintrack_1 extends javax.swing.JFrame {

    /**
     * Creates new form j_fintrack
     */
    private static final String username = "root";
    private static final String password = "Sql1234*";
    private static final String dataConn = "jdbc:mysql://localhost:3306/java_users_db";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    public java_fintrack_1() {
        initComponents();
    }
    public void upDateDB() {
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("select * from my_fintrack WHERE user_id=?");
            pst.setInt(1,Login.userId);
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while(rs.next()) {
                Vector columnData = new Vector();

                for (i = 1; i <= q; i++) {
        		columnData.add(rs.getString("id"));
                        columnData.add(rs.getString("whether_expenditure"));
        		columnData.add(rs.getString("description"));
                        columnData.add(rs.getString("amount"));
        		columnData.add(rs.getString("dt"));
        	
    		}
		RecordTable.addRow(columnData);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtDescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtExp = new javax.swing.JTextField();
        jcomboExp = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnAddnew = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Piechart = new javax.swing.JButton();
        jbtnReports = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 10));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 10, true));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("[E]Expenditure/[I]Income");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Description");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, -1));

        jtxtDescription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jPanel3.add(jtxtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 430, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Amount");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, -1));

        jtxtAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jPanel3.add(jtxtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 310, -1));

        jTable1.setBackground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "whether_expenditure", "description", "amount", "dt"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 670, 220));

        jtxtDate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 310, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Date");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, -1));

        jtxtExp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jPanel3.add(jtxtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 190, -1));

        jcomboExp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "I" }));
        jcomboExp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true));
        jcomboExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboExpActionPerformed(evt);
            }
        });
        jPanel3.add(jcomboExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jButton1.setText("Balance");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 240, 0));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 293, 670, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 700, 540));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 10, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        jbtnAddnew.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnAddnew.setText("Add New");
        jbtnAddnew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jbtnAddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddnewActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 160, 40));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, -1));

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("   Reports");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 120, 30));

        Piechart.setText("Pie Chart");
        Piechart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        Piechart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiechartActionPerformed(evt);
            }
        });
        jPanel4.add(Piechart, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 90, 30));

        jbtnReports.setText("Bar Chart ");
        jbtnReports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        jbtnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReportsActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 120, 210, 540));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("FINTRACK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 280, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel8.setText("Darsh Goswami, Deepanjana Mishra, Dhruv Gadia, Divyanshu");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 260, 10));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 900, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 950, 680));
        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
         frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "FINTRACK",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jcomboExp.setSelectedIndex(0);
        jtxtExp.setText("");
        jtxtDescription.setText("");
        jtxtAmount.setText("");
        jtxtDate.setText("");
       
        

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnAddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddnewActionPerformed
        try {
            System.out.println(Login.userId);
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("insert into my_fintrack (whether_expenditure,description,amount,dt,user_id"
                + ")VALUES(?,?,?,?,?)");

            pst.setString(1, jtxtExp.getText());
            pst.setString(2, jtxtDescription.getText());
            pst.setString(3, jtxtAmount.getText());
            pst.setString(4, jtxtDate.getText());
            pst.setInt(5, Login.userId);
       
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDB();
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbtnAddnewActionPerformed

    private void jcomboExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboExpActionPerformed
        String selectedValue = jcomboExp.getSelectedItem().toString();
            jtxtExp.setText(selectedValue);
    }//GEN-LAST:event_jcomboExpActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
    DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("update my_fintrack set whether_expenditure=?, description=?, amount=?, dt=? where id=? AND user_id=?");

            pst.setString(1, jtxtExp.getText());
            pst.setString(2, jtxtDescription.getText());
            pst.setString(3, jtxtAmount.getText());
            pst.setString(4, jtxtDate.getText());
            pst.setInt(5, id);
            pst.setInt(6,Login.userId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB();
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
               DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
               int SelectedRows = jTable1.getSelectedRow();
               
                jtxtExp.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                jtxtDescription.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                jtxtAmount.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
                jtxtDate.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        upDateDB();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("delete from my_fintrack where id =? AND user_id=?");
            pst.setInt(1, id);
            pst.setInt(2,Login.userId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB();
            jtxtExp.setText("");
            jtxtExp.requestFocus();
            jtxtDescription.setText("");
            jtxtAmount.setText("");
            jtxtDate.setText("");
            
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("select sum(amount) from my_fintrack where whether_expenditure='I' AND user_id=?");
            pst.setInt(1,Login.userId);
            ResultSet rs = pst.executeQuery();
            float income=0;
            if (rs.next()) {
            income = rs.getFloat(1); // Retrieve the sum of income
            }
            
            //float income = pst.getFloat("sum(amount)");
            //JOptionPane.showMessageDialog(null,"Income:" + rs);
            
            pst = sqlConn.prepareStatement("select sum(amount) from my_fintrack where whether_expenditure='E' AND user_id=?");
            pst.setInt(1,Login.userId);
            rs=pst.executeQuery();
            float expense = 0;
            if (rs.next()) {
            expense = rs.getFloat(1); // Retrieve the sum of expenses
            }
            float balance = income - expense;
            JOptionPane.showMessageDialog(null, "Current Balance: " + balance);
            
            } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
       //JOptionPane.showMessageDialog(this, "Print balance here...");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReportsActionPerformed
        //ReportsPanel reports = new ReportsPanel();
        //reports.setVisible(true);
       
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        Connection con;
        PreparedStatement pst;
        ResultSet rs;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_users_db", "root", "Sql1234*");

            String query = "SELECT description, amount FROM my_fintrack WHERE user_id = ?";
            pst = con.prepareStatement(query);
            pst.setInt(1, Login.userId); 
            //pst.setInt(2,Login.userId);// <-- Key line
            rs = pst.executeQuery();

            while (rs.next()) {
                dataset.setValue(rs.getDouble("amount"), "Amount", rs.getString("description"));
            }

            JFreeChart chart = ChartFactory.createBarChart3D("Expense Chart", "Category", "Amount", dataset, PlotOrientation.VERTICAL, false, true, false);
            ChartFrame frame = new ChartFrame("User Report", chart);
            frame.setVisible(true);
            frame.setBounds(450, 90, 700, 680);
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        
    }//GEN-LAST:event_jbtnReportsActionPerformed

    private void PiechartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiechartActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset dataset = new DefaultPieDataset();

        Connection con;
        PreparedStatement pst;
        ResultSet rs;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_users_db", "root", "Sql1234*");

            String query = "SELECT description, amount FROM my_fintrack WHERE user_id = ?";
            pst = con.prepareStatement(query);
            pst.setInt(1, Login.userId); 
            //pst.setInt(2,Login.userId);// <-- Key line
            rs = pst.executeQuery();

            while (rs.next()) {
                dataset.setValue(rs.getString("description"),rs.getDouble("amount"));          
            }

            JFreeChart chart = ChartFactory.createPieChart("Expense Chart", dataset, true, true,false);
            

            // 🔧 Customize the pie plot
            PiePlot plot = (PiePlot) chart.getPlot();

            // Set the background color (optional)
            plot.setBackgroundPaint(Color.LIGHT_GRAY);

            // 🔹 Label link (arrow) style
            plot.setLabelLinkPaint(Color.BLACK); // Arrow color
            plot.setLabelLinkStroke(new BasicStroke(2.0f)); // Arrow thickness
            plot.setLabelOutlinePaint(null); // Remove label box border
            plot.setLabelBackgroundPaint(new Color(255, 255, 200)); // Label background color
            plot.setLabelShadowPaint(null); // Remove shadow

            ChartFrame frame = new ChartFrame("User Report", chart);
            frame.setVisible(true);
            frame.setBounds(450, 90, 700, 680);
            
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_PiechartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java_fintrack_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java_fintrack_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java_fintrack_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java_fintrack_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Login LoginFrame = new Login(); 
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new java_fintrack().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Piechart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddnew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReports;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcomboExp;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtExp;
    // End of variables declaration//GEN-END:variables
}
